apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Alertmanager"
metadata:
  name: {{ template "alertmanager.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "alertmanager"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"     
    alertmanager: {{ template "alertmanager.fullname" . }}
spec:
  replicas: 3
  version: v0.5.0
